apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal: "21186"
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-p9oq3uc1
  labels:
    component: elasticsearch
    role: client
  name: elasticsearch
  namespace: devops
spec:
  clusterIP: 172.20.255.27
  ports:
  - name: http
    nodePort: 30433
    port: 9200
    protocol: TCP
    targetPort: 9200
  selector:
    component: elasticsearch
    role: client
  sessionAffinity: None
  type: LoadBalancer
