apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: graylog-node
  namespace: devops
  labels:
    component: graylog
    role: graylog-node
spec:
  replicas: 3
  selector:
    matchLabels:
      component: graylog
      role: graylog-node
  template:
    metadata:
      labels:
        component: graylog
        role: graylog-node
    spec:
      containers:
      - name: graylog
        image: ccr.ccs.tencentyun.com/zhulux_sre/graylog:v2.3.0
        ports:
        - containerPort: 12300
          name: udp
          protocol: UDP
        - containerPort: 9000
          name: graylog-api
          protocol: TCP
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: "GRAYLOG_ELASTICSEARCH_HOSTS"
          value: "http://elasticsearch:9200/"
        - name: "GRAYLOT_ELASTICSEARCH_DISCOVERY_ENABLED"
          value: "true"
        - name: "GRAYLOG_MONGODB_URI"
          value: "mongodb://mongo:27017/graylog"
        - name: "GRAYLOG_ROOT_TIMEZONE"
          value: "Asia/Shanghai"
        - name: "GRAYLOG_IS_MASTER"
          value: "false"
        - name: "GRAYLOG_WEB_ENABLE"
          value: "false"
        - name: "GRAYLOG_OUTPUT_BATCH_SIZE"
          value: "5000"
      imagePullSecrets:
      - name: qcloudregistrykey
