apiVersion: v1
kind: Service
metadata:
  annotations:
    service.kubernetes.io/qcloud-loadbalancer-internal: "21186"
    service.kubernetes.io/qcloud-loadbalancer-internal-subnetid: subnet-p9oq3uc1
  labels:
    component: graylog
    role: master
  name: graylog
  namespace: devops
spec:
  clusterIP: 172.20.255.33
  ports:
  - name: http
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: apiport
    port: 12900
    protocol: TCP
    targetPort: 12900
  - name: tcpin
    port: 12300
    targetPort: 12300
    protocol: TCP
  - name: tcpin1
    port: 12301
    targetPort: 12301
    protocol: TCP
  - name: tcpin2
    port: 12302
    targetPort: 12302
    protocol: TCP
  - name: tcpin3
    port: 12303
    targetPort: 12303
    protocol: TCP
  selector:
    component: graylog
    role: master
  sessionAffinity: None
  type: LoadBalancer
