apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  namespace: devops
  labels:
    component: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mongo
  template:
    metadata:
      labels:
        component: mongo
    spec:
      containers:
      - name: mongo
        image: ccr.ccs.tencentyun.com/zhulux_sre/mongo:3
        ports:
        - containerPort: 27017
          name: tcp
          protocol: TCP
        volumeMounts:
        - name: nfs
          mountPath: /data/db
      imagePullSecrets:
      - name: qcloudregistrykey
      volumes:
      - name: nfs
        nfs:
            server: 172.17.255.16
            path: "/mongodb"
