apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: devops
  labels:
    component: mongo
spec:
  selector:
    component: mongo
  ports:
    - name: db
      port: 27017
      protocol: TCP
    
